# Generated by Django 5.0.4 on 2024-04-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
