# Generated by Django 4.2.11 on 2024-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_img_remove_post_user_name_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='user_id',
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='session_id',
            field=models.UUIDField(null=True),
        ),
    ]
